# Generated by Django 4.2.29 on 2026-04-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salary_percent',
            field=models.DecimalField(decimal_places=2, default=7, help_text='Процент от суммы продаж, начисляемый как зарплата', max_digits=5, verbose_name='% от продаж (ЗП)'),
        ),
    ]
