# Generated by Django 4.2.29 on 2026-03-09 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('specialty', models.CharField(max_length=100, verbose_name='Специализация')),
                ('institution', models.CharField(max_length=200, verbose_name='Медучреждение')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Адрес')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название аптеки')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='Контактное лицо')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Задолженность')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Аптека',
                'verbose_name_plural': 'Аптеки',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(choices=[('doctor', 'Врач'), ('pharmacy', 'Аптека')], max_length=10, verbose_name='Тип визита')),
                ('status', models.CharField(choices=[('planned', 'Запланирован'), ('done', 'Выполнен'), ('cancelled', 'Отменён'), ('postponed', 'Перенесён')], default='planned', max_length=15, verbose_name='Статус')),
                ('planned_date', models.DateTimeField(verbose_name='Плановая дата')),
                ('actual_date', models.DateTimeField(blank=True, null=True, verbose_name='Фактическая дата')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('result', models.TextField(blank=True, verbose_name='Результат')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.doctor', verbose_name='Врач')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('pharmacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.pharmacy', verbose_name='Аптека')),
            ],
            options={
                'verbose_name': 'Визит',
                'verbose_name_plural': 'Визиты',
                'ordering': ['-planned_date'],
            },
        ),
        migrations.CreateModel(
            name='VisitPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='visit_photos/%Y/%m/', verbose_name='Фото')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='crm.visit')),
            ],
            options={
                'verbose_name': 'Фотоотчет',
            },
        ),
        migrations.CreateModel(
            name='VisitAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='visit_audio/%Y/%m/', verbose_name='Аудиозапись')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='crm.visit')),
            ],
            options={
                'verbose_name': 'Аудиозапись',
            },
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.region', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pharmacies', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.region', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_doctors', to=settings.AUTH_USER_MODEL, verbose_name='Представитель'),
        ),
        migrations.CreateModel(
            name='VisitPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='Месяц')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('planned_visits', models.IntegerField(default=0, verbose_name='План визитов')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'План визитов',
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
