# Generated by Django 4.2.29 on 2026-04-08 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_paid_amount_sale_receipt_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: ИП «Арапова Арзихан Хакимовна»', max_length=300, verbose_name='Полное наименование')),
                ('entity_type', models.CharField(choices=[('ip', 'ИП'), ('osoo', 'ОсОО'), ('oao', 'ОАО'), ('zao', 'ЗАО'), ('other', 'Другое')], default='ip', max_length=10, verbose_name='Тип')),
                ('address', models.CharField(blank=True, max_length=400, verbose_name='Адрес')),
                ('bank', models.CharField(blank=True, max_length=300, verbose_name='Банк')),
                ('account', models.CharField(blank=True, max_length=100, verbose_name='Р/сч')),
                ('bik', models.CharField(blank=True, max_length=30, verbose_name='БИК')),
                ('inn', models.CharField(blank=True, max_length=50, verbose_name='ИНН')),
                ('certificate', models.CharField(blank=True, help_text='Например: №НС150153 от 24.04.2022', max_length=200, verbose_name='Свидетельство')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
            ],
            options={
                'verbose_name': 'Юридическое лицо',
                'verbose_name_plural': 'Юридические лица',
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер накладной'),
        ),
        migrations.AddField(
            model_name='sale',
            name='legal_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.legalentity', verbose_name='Юр. лицо (продавец)'),
        ),
    ]
